CREATE USER WEBAPP IDENTIFIED BY PI2Grupo15$$;
GRANT CREATE SESSION TO WEBAPP;
GRANT CREATE TABLE TO WEBAPP;
GRANT CREATE SEQUENCE TO WEBAPP;
GRANT CREATE TRIGGER TO WEBAPP;

SELECT username, authentication_type
FROM dba_users WHERE username = 'WEBAPP';

ALTER USER WEBAPP
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP;

ALTER USER WEBAPP QUOTA 100M ON DATA;

SELECT username, default_tablespace, temporary_tablespace
FROM dba_users
WHERE username = 'WEBAPP';

SELECT tablespace_name, bytes, max_bytes
FROM dba_ts_quotas
WHERE username = 'WEBAPP';

CREATE SEQUENCE seq_instituicoes START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_cursos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_disciplinas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_turmas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_professores START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_componente_nota START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_nota START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_auditoria START WITH 1 INCREMENT BY 1;

CREATE TABLE PROFESSORES (
 id_professor NUMBER PRIMARY KEY,
 nome VARCHAR2(100) NOT NULL,
 telefone VARCHAR2(20),
 senha VARCHAR2(100),
 email VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE INSTITUICOES (
id_instituicao NUMBER PRIMARY KEY,
nome VARCHAR2(200) NOT NULL,
id_PROFESSOR Number NOT NULL,
CONSTRAINT fk_instituicao_professor
FOREIGN KEY (id_professor) REFERENCES PROFESSORES(id_professor)

);

CREATE TABLE CURSOS (
id_curso NUMBER PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
codigo VARCHAR2(20) NOT NULL,
id_instituicao NUMBER NOT NULL,
CONSTRAINT fk_curso_instituicao
FOREIGN KEY (id_instituicao) REFERENCES INSTITUICOES(id_instituicao)
);

CREATE TABLE DISCIPLINAS (
id_disciplina NUMBER PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
sigla VARCHAR2(10) NOT NULL,
codigo VARCHAR2(20) UNIQUE NOT NULL,
periodo NUMBER,
id_curso NUMBER NOT NULL,
CONSTRAINT fk_disciplina_curso
FOREIGN KEY (id_curso) REFERENCES CURSOS(id_curso)
);

CREATE TABLE TURMAS (
id_turma NUMBER PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
codigo VARCHAR2(20),
turno VARCHAR2(10),
id_disciplina NUMBER NOT NULL,
CONSTRAINT fk_turma_disciplina
FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINAS(id_disciplina)
);

CREATE TABLE ALUNOS (
RA_aluno VARCHAR2(20) PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
data_nascimento DATE,
id_turma NUMBER NOT NULL,
CONSTRAINT fk_aluno_turma
FOREIGN KEY (id_turma) REFERENCES TURMAS(id_turma)
);

CREATE TABLE COMPONENTE_NOTA (
id_componente NUMBER PRIMARY KEY,
nome VARCHAR2(50) NOT NULL,
sigla VARCHAR2(10),
descricao VARCHAR2(200),
id_disciplina NUMBER NOT NULL,
CONSTRAINT fk_comp_disciplina
FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINAS(id_disciplina)
);

CREATE TABLE NOTA (
id_nota NUMBER PRIMARY KEY,
valor NUMBER(4, 2),
id_componente NUMBER NOT NULL,
RA_aluno VARCHAR2(20) NOT NULL,
CONSTRAINT fk_nota_componente
FOREIGN KEY (id_componente) REFERENCES COMPONENTE_NOTA(id_componente),
CONSTRAINT fk_nota_aluno
FOREIGN KEY (RA_aluno) REFERENCES ALUNOS(RA_aluno)
);

CREATE TABLE AUDITORIA (
id_auditoria NUMBER PRIMARY KEY,
data_hora TIMESTAMP DEFAULT SYSTIMESTAMP,
descricao VARCHAR2(500),
id_nota NUMBER,
CONSTRAINT fk_auditoria_nota
FOREIGN KEY (id_nota) REFERENCES NOTA(id_nota));
CREATE TABLE TURMAS_ALUNOS (
id_turma NUMBER NOT NULL,
RA_aluno VARCHAR2(20) NOT NULL,
PRIMARY KEY (id_turma, RA_aluno),
CONSTRAINT fk_ta_turma FOREIGN KEY (id_turma) REFERENCES TURMAS(id_turma),
CONSTRAINT fk_ta_aluno FOREIGN KEY (RA_aluno) REFERENCES ALUNOS(RA_aluno)
);

CREATE OR REPLACE TRIGGER trg_professores_pk
BEFORE INSERT ON PROFESSORES
FOR EACH ROW
WHEN (NEW.id_professor IS NULL)
BEGIN
  SELECT seq_professores.NEXTVAL INTO :NEW.id_professor FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_instituicoes_pk
BEFORE INSERT ON INSTITUICOES
FOR EACH ROW
WHEN (NEW.id_instituicao IS NULL)
BEGIN
  SELECT seq_instituicoes.NEXTVAL INTO :NEW.id_instituicao FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_cursos_pk
BEFORE INSERT ON CURSOS
FOR EACH ROW
WHEN (NEW.id_curso IS NULL)
BEGIN
  SELECT seq_cursos.NEXTVAL INTO :NEW.id_curso FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_disciplinas_pk
BEFORE INSERT ON DISCIPLINAS
FOR EACH ROW
WHEN (NEW.id_disciplina IS NULL)
BEGIN
  SELECT seq_disciplinas.NEXTVAL INTO :NEW.id_disciplina FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_turmas_pk
BEFORE INSERT ON TURMAS
FOR EACH ROW
WHEN (NEW.id_turma IS NULL)
BEGIN
  SELECT seq_turmas.NEXTVAL INTO :NEW.id_turma FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_componente_nota_pk
BEFORE INSERT ON COMPONENTE_NOTA
FOR EACH ROW
WHEN (NEW.id_componente IS NULL)
BEGIN
  SELECT seq_componente_nota.NEXTVAL INTO :NEW.id_componente FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_nota_pk
BEFORE INSERT ON NOTA
FOR EACH ROW
WHEN (NEW.id_nota IS NULL)
BEGIN
  SELECT seq_nota.NEXTVAL INTO :NEW.id_nota FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_auditoria_pk
BEFORE INSERT ON AUDITORIA
FOR EACH ROW
WHEN (NEW.id_auditoria IS NULL)
BEGIN
  SELECT seq_auditoria.NEXTVAL INTO :NEW.id_auditoria FROM DUAL;
END;
/

COMMIT;

INSERT INTO PROFESSORES (nome, telefone, senha, email) VALUES ('Renata', '123456789', 'password123', 'renata@example.com');

COMMIT;